### ISSUE TITLE
Operating independently of Eclipse

### ISSUE THREAD

**Issue by nathanaeljones** [slluis/sharpen#54]
Does anyone have any suggestions for creating a command-line version of sharpen that does not have an Eclipse dependency? (Such as for use on a build server). Any suggestions for a replacement source code parser system?

https://github.com/INRIA/spoon
http://www.monperrus.net/martin/jexast
https://github.com/matozoid/javaparser
http://docs.oracle.com/javase/7/docs/jdk/api/javac/tree/com/sun/source/tree/package-summary.html

**Comment by nathanaeljones** [comment]
We've made quite a few bug fixes: https://github.com/imazen/sharpen/tree/commandline

Usage is still poorly understood/documented.

**Comment by JosephEarl** [comment]
@nathanaeljones great work!
